### ISSUE TITLE
Changes needed to nf-core pipeline template `.github` folder

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/nf-core-pipeline#1]
`.github` – https://github.com/nf-core/tools/tree/master/nf_core/pipeline-template/.github
Discuss what needs to be modified to get GitHub actions in sync with Sanger ToL development.

**Comment by priyanka-surana** [comment]
[awstest.yml](https://github.com/nf-core/tools/blob/master/nf_core/pipeline-template/.github/workflows/awstest.yml) and [awsfulltest.yml](https://github.com/nf-core/tools/blob/master/nf_core/pipeline-template/.github/workflows/awsfulltest.yml)

- Read from s3 bucket
- Modify to run on farm5 via nf-tower
- Write to s3 bucket and make public

 Does that seem doable?

**Comment by muffato** [comment]
Summary of the discussion this morning:
- https://tower.nf/ supports LSF but needs to be able to SSH into it, which is not possible because our farms are behind the firewall
- Same story for Kubernetes: there needs to be a public URL https://tower.nf/ can talk to.

It might be possible to adapt the whole thing if we mirror the repository onto GitLab, and use the GitLab CI instead of GitHub's. We can talk to Seqera and see if they know how to do that, but also need to confirm what we would gain from having the integration vs keep on using the command-line.

**Comment by muffato** [comment]
Our Kubernetes cluster is not appropriate for compute, so we should only consider the farm. On the call on Monday they mentioned "Tower agents", https://github.com/seqeralabs/tower-agent, which seems to be exactly the way of making a private HPC visible on the public tower.nf. Martin Prete confirmed they managed to set this up.
The alternative is to deploy a _GitHub_ agent onto the farm, and run `nextflow run` through it, like in `ci.yml`. They're essentially the same principle: get a service running on the farm, that allows those external platforms (tower.nf and github.com) to run stuff on it from the outside.

I would also prefer not running the tests on S3, not only because we've had issues with it (TOLIT-549), but also because it's inherently far slower than Lustre, and it's not a storage platform we're targeting.

We need to answer a few questions:
 - Do we need to test the pipeline via Tower ? What makes this test useful ?
 - What's the expected size / runtime of the "test" and "full test" profiles ? Why run two tests ? If we use GitHub CI for a test, we need to make it clear in the documentation that it has to run within X hours and Y GB RAM on Z cores

**Comment by priyanka-surana** [comment]
– I think it is useful because it is automated. Not everyone tests their code, especially incrementally and this forces them to follow good practices.

– The "test" is going to be unit test, this generally takes less than 5 minutes and doesn't need more than 2 cpus and 4 GB RAM. This doesn't require tower, we should be able to do this in GitHub itself.
– The "full test" is generally our smallest test, just to run a full real sample and get a real result. This will require tower/farm. And if we want we can limit it, instead of every commit, we can run It only when a merge happens from feature to dev or similar.
